# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='overview',
            field=models.CharField(default='Overview', max_length=32, verbose_name='\u9884\u89c8'),
        ),
    ]
