# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
